package com.home.mexico.empleado;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2019-05-15T18:20:57.104-05:00
 * Generated source version: 3.3.0
 *
 */
@WebService(targetNamespace = "http://www.mexico.home.com/empleado/", name = "EmpleadoService")
@XmlSeeAlso({com.home.mexico.abelhzo.common.ObjectFactory.class, com.home.mexico.empleado.operaciones.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface EmpleadoService {

    @WebMethod(operationName = "EmpleadoListar", action = "http://www.mexico.home.com/empleado/")
    @WebResult(name = "EmpleadoListarRs", targetNamespace = "http://www.mexico.home.com/empleado/operaciones/", partName = "EmpleadoListarRs")
    public com.home.mexico.empleado.operaciones.EmpleadoListarRs empleadoListar(
        @WebParam(partName = "EmpleadoListarRq", name = "EmpleadoListarRq", targetNamespace = "http://www.mexico.home.com/empleado/operaciones/")
        com.home.mexico.empleado.operaciones.EmpleadoListarRq empleadoListarRq
    );

    @WebMethod(operationName = "EmpleadoGuardar", action = "http://www.mexico.home.com/empleado/")
    @WebResult(name = "EmpleadoGuardarRs", targetNamespace = "http://www.mexico.home.com/empleado/operaciones/", partName = "EmpleadoGuardarRs")
    public com.home.mexico.empleado.operaciones.EmpleadoGuardarRs empleadoGuardar(
        @WebParam(partName = "EmpleadoGuardarRq", name = "EmpleadoGuardarRq", targetNamespace = "http://www.mexico.home.com/empleado/operaciones/")
        com.home.mexico.empleado.operaciones.EmpleadoGuardarRq empleadoGuardarRq
    );

    @WebMethod(operationName = "EmpleadoBuscar", action = "http://www.mexico.home.com/empleado/")
    @WebResult(name = "EmpleadoBuscarRs", targetNamespace = "http://www.mexico.home.com/empleado/operaciones/", partName = "EmpleadoBuscarRs")
    public com.home.mexico.empleado.operaciones.EmpleadoBuscarRs empleadoBuscar(
        @WebParam(partName = "EmpleadoBuscarRq", name = "EmpleadoBuscarRq", targetNamespace = "http://www.mexico.home.com/empleado/operaciones/")
        com.home.mexico.empleado.operaciones.EmpleadoBuscarRq empleadoBuscarRq
    );

    @WebMethod(operationName = "EmpleadoModificar", action = "http://www.mexico.home.com/empleado/")
    @WebResult(name = "EmpleadoModificarRs", targetNamespace = "http://www.mexico.home.com/empleado/operaciones/", partName = "EmpleadoModificarRs")
    public com.home.mexico.empleado.operaciones.EmpleadoModificarRs empleadoModificar(
        @WebParam(partName = "EmpleadoModificarRq", name = "EmpleadoModificarRq", targetNamespace = "http://www.mexico.home.com/empleado/operaciones/")
        com.home.mexico.empleado.operaciones.EmpleadoModificarRq empleadoModificarRq
    );
}
