package com.home.mexico.departamento;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2019-05-15T18:20:58.265-05:00
 * Generated source version: 3.3.0
 *
 */
@WebServiceClient(name = "DepartamentoServiceClient",
                  wsdlLocation = "src/main/resources/departamentos/departamentos.wsdl",
                  targetNamespace = "http://www.mexico.home.com/departamento/")
public class DepartamentoServiceClient extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.mexico.home.com/departamento/", "DepartamentoServiceClient");
    public final static QName DepartamentoListarSOAP = new QName("http://www.mexico.home.com/departamento/", "departamentoListarSOAP");
    static {
        URL url = DepartamentoServiceClient.class.getResource("src/main/resources/departamentos/departamentos.wsdl");
        if (url == null) {
            url = DepartamentoServiceClient.class.getClassLoader().getResource("src/main/resources/departamentos/departamentos.wsdl");
        }
        if (url == null) {
            java.util.logging.Logger.getLogger(DepartamentoServiceClient.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "src/main/resources/departamentos/departamentos.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public DepartamentoServiceClient(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DepartamentoServiceClient(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DepartamentoServiceClient() {
        super(WSDL_LOCATION, SERVICE);
    }

    public DepartamentoServiceClient(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public DepartamentoServiceClient(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public DepartamentoServiceClient(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns DepartamentoService
     */
    @WebEndpoint(name = "departamentoListarSOAP")
    public DepartamentoService getDepartamentoListarSOAP() {
        return super.getPort(DepartamentoListarSOAP, DepartamentoService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DepartamentoService
     */
    @WebEndpoint(name = "departamentoListarSOAP")
    public DepartamentoService getDepartamentoListarSOAP(WebServiceFeature... features) {
        return super.getPort(DepartamentoListarSOAP, DepartamentoService.class, features);
    }

}
